# Generated by Django 3.2.23 on 2023-11-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(db_column='nama', max_length=100)),
                ('Alamat', models.TextField(db_column='alamat', max_length=1000)),
                ('Nohp', models.CharField(db_column='nohp', max_length=100)),
                ('Join_Member', models.CharField(db_column='join_member', default=2000, max_length=100)),
                ('Habis_Member', models.CharField(db_column='habis_member', default=2000, max_length=100)),
            ],
        ),
    ]
