# Generated by Django 3.2.23 on 2023-11-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_qrcode_qr_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
